version: '3.5'
services:
  web:
    container_name: demo-app
    restart: always
    image: pauljflo/tattoo
    volumes:
      - /etc/hosts:/etc/hosts
    ports:
      - "8080:80"
networks:
  default:
    name: demo-local
